language: R
cache: packages
sudo: true
os: 
  - linux


r:
  - release
  - devel

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
  
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search
